package com.hoandev.pinedrink.mapper;

import com.hoandev.pinedrink.entity.Branch;
import com.hoandev.pinedrink.entity.Brand;
import com.hoandev.pinedrink.entity.dto.request.Branch.CreateBranchRequest;
import com.hoandev.pinedrink.entity.dto.request.Branch.UpdateBranchRequest;
import com.hoandev.pinedrink.entity.dto.response.Branch.BranchResponse;
import org.springframework.stereotype.Component;

/**
 * Mapper for Branch entity and DTOs.
 */
@Component
public class BranchMapper {

    /**
     * Maps Branch entity to BranchResponse DTO.
     *
     * @param branch the branch entity
     * @return the branch response DTO
     */
    public BranchResponse toResponse(Branch branch) {
        if (branch == null) {
            return null;
        }

        return BranchResponse.builder()
                .id(branch.getId())
                .code(branch.getCode())
                .name(branch.getName())
                .address(branch.getAddress())
                .phone(branch.getPhone())
                .email(branch.getEmail())
                .latitude(branch.getLatitude())
                .longitude(branch.getLongitude())
                .timezone(branch.getTimezone())
                .supportsPickup(branch.isSupportsPickup())
                .supportsDelivery(branch.isSupportsDelivery())
                .averagePreparationMinutes(branch.getAveragePreparationMinutes())
                .brandId(branch.getBrand() != null ? branch.getBrand().getId() : null)
                .brandName(branch.getBrand() != null ? branch.getBrand().getName() : null)
                .status(branch.getStatus())
                .createdAt(branch.getCreatedAt())
                .updatedAt(branch.getUpdatedAt())
                .build();
    }

    /**
     * Maps CreateBranchRequest to Branch entity.
     *
     * @param request the create branch request
     * @param brand the brand entity
     * @return the branch entity
     */
    public Branch toEntity(CreateBranchRequest request, Brand brand) {
        if (request == null) {
            return null;
        }

        Branch branch = new Branch();
        // Code will be generated by CodeGenerator in service layer
        branch.setName(request.getName());
        branch.setAddress(request.getAddress());
        branch.setPhone(request.getPhone());
        branch.setEmail(request.getEmail());
        branch.setLatitude(request.getLatitude());
        branch.setLongitude(request.getLongitude());
        branch.setTimezone(request.getTimezone());
        branch.setSupportsPickup(request.isSupportsPickup());
        branch.setSupportsDelivery(request.isSupportsDelivery());
        branch.setAveragePreparationMinutes(request.getAveragePreparationMinutes());
        branch.setBrand(brand);
        return branch;
    }

    /**
     * Updates Branch entity from UpdateBranchRequest.
     *
     * @param branch the branch entity to update
     * @param request the update branch request
     */
    public void updateEntity(Branch branch, UpdateBranchRequest request) {
        if (branch == null || request == null) {
            return;
        }

        if (request.getName() != null) {
            branch.setName(request.getName());
        }
        if (request.getAddress() != null) {
            branch.setAddress(request.getAddress());
        }
        if (request.getPhone() != null) {
            branch.setPhone(request.getPhone());
        }
        if (request.getEmail() != null) {
            branch.setEmail(request.getEmail());
        }
        if (request.getLatitude() != null) {
            branch.setLatitude(request.getLatitude());
        }
        if (request.getLongitude() != null) {
            branch.setLongitude(request.getLongitude());
        }
        if (request.getTimezone() != null) {
            branch.setTimezone(request.getTimezone());
        }
        if (request.getSupportsPickup() != null) {
            branch.setSupportsPickup(request.getSupportsPickup());
        }
        if (request.getSupportsDelivery() != null) {
            branch.setSupportsDelivery(request.getSupportsDelivery());
        }
        if (request.getAveragePreparationMinutes() != null) {
            branch.setAveragePreparationMinutes(request.getAveragePreparationMinutes());
        }
    }
}
