-- Pine Drink - Order schema

CREATE TABLE od_order (
    id CHAR(36) NOT NULL PRIMARY KEY,
    order_code VARCHAR(50) NOT NULL,
    branch_id CHAR(36) NOT NULL,
    customer_id CHAR(36) NULL,
    customer_name VARCHAR(150) NOT NULL,
    customer_phone VARCHAR(20) NOT NULL,
    customer_email VARCHAR(150) NULL,
    order_type VARCHAR(30) NOT NULL DEFAULT 'PICKUP',
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    payment_method VARCHAR(50) NULL,
    payment_status VARCHAR(30) NOT NULL DEFAULT 'UNPAID',
    subtotal_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    discount_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    delivery_fee DECIMAL(12,2) NOT NULL DEFAULT 0,
    total_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    pickup_time DATETIME NULL,
    delivery_address VARCHAR(255) NULL,
    note VARCHAR(500) NULL,
    confirmed_at DATETIME NULL,
    prepared_at DATETIME NULL,
    ready_at DATETIME NULL,
    delivering_at DATETIME NULL,
    delivered_at DATETIME NULL,
    completed_at DATETIME NULL,
    cancelled_at DATETIME NULL,
    rejected_at DATETIME NULL,
    cancel_reason VARCHAR(255) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by CHAR(36) NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_by CHAR(36) NULL,
    UNIQUE KEY uk_od_order_code (order_code),
    CONSTRAINT fk_od_order_branch FOREIGN KEY (branch_id) REFERENCES ce_branch(id) ON DELETE RESTRICT,
    CONSTRAINT fk_od_order_customer FOREIGN KEY (customer_id) REFERENCES cu_customer_profile(id) ON DELETE SET NULL,
    INDEX idx_od_order_customer_created (customer_id, created_at),
    INDEX idx_od_order_branch_created (branch_id, created_at),
    INDEX idx_od_order_branch_status_created (branch_id, status, created_at),
    INDEX idx_od_order_branch_type_status_created (branch_id, order_type, status, created_at),
    INDEX idx_od_order_branch_payment_created (branch_id, payment_method, created_at),
    INDEX idx_od_order_branch_payment_status_created (branch_id, payment_status, created_at),
    CHECK (status IN ('PENDING', 'CONFIRMED', 'PREPARING', 'READY', 'DELIVERING', 'COMPLETED', 'CANCELLED', 'REJECTED')),
    CHECK (payment_method IS NULL OR payment_method IN ('CASH', 'COD', 'VNPAY', 'MOMO', 'BANK_TRANSFER')),
    CHECK (subtotal_amount >= 0),
    CHECK (discount_amount >= 0),
    CHECK (delivery_fee >= 0),
    CHECK (total_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE od_order_delivery (
    id CHAR(36) NOT NULL PRIMARY KEY,
    order_id CHAR(36) NOT NULL,
    shipper_id CHAR(36) NULL,
    receiver_name VARCHAR(150) NOT NULL,
    receiver_phone VARCHAR(20) NOT NULL,
    delivery_address VARCHAR(255) NOT NULL,
    delivery_note VARCHAR(500) NULL,
    delivery_fee DECIMAL(12,2) NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    assigned_at DATETIME NULL,
    picked_up_at DATETIME NULL,
    delivered_at DATETIME NULL,
    failed_at DATETIME NULL,
    fail_reason VARCHAR(255) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by CHAR(36) NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_by CHAR(36) NULL,
    UNIQUE KEY uk_od_order_delivery_order (order_id),
    CONSTRAINT fk_od_order_delivery_order FOREIGN KEY (order_id) REFERENCES od_order(id) ON DELETE CASCADE,
    CONSTRAINT fk_od_order_delivery_shipper FOREIGN KEY (shipper_id) REFERENCES ia_account(id) ON DELETE SET NULL,
    INDEX idx_od_order_delivery_shipper_status_created (shipper_id, status, created_at),
    INDEX idx_od_order_delivery_status_created (status, created_at),
    CHECK (delivery_fee >= 0),
    CHECK (status IN ('PENDING', 'ASSIGNED', 'PICKED_UP', 'DELIVERING', 'DELIVERED', 'FAILED', 'CANCELLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE od_order_item (
    id CHAR(36) NOT NULL PRIMARY KEY,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    order_id CHAR(36) NOT NULL,
    product_id CHAR(36) NULL,
    variant_id CHAR(36) NULL,
    product_code VARCHAR(50) NOT NULL,
    product_name VARCHAR(150) NOT NULL,
    variant_name VARCHAR(100) NULL,
    quantity INT NOT NULL,
    sugar_level VARCHAR(30) NOT NULL DEFAULT 'NORMAL',
    ice_level VARCHAR(30) NOT NULL DEFAULT 'NORMAL',
    note VARCHAR(255) NULL,
    unit_price DECIMAL(12,2) NOT NULL,
    total_price DECIMAL(12,2) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by CHAR(36) NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_by CHAR(36) NULL,
    CONSTRAINT fk_od_item_order FOREIGN KEY (order_id) REFERENCES od_order(id) ON DELETE CASCADE,
    CONSTRAINT fk_od_item_product FOREIGN KEY (product_id) REFERENCES pr_product(id) ON DELETE SET NULL,
    CONSTRAINT fk_od_item_variant FOREIGN KEY (variant_id) REFERENCES pr_product_variant(id) ON DELETE SET NULL,
    INDEX idx_od_item_order (order_id),
    INDEX idx_od_item_product (product_id),
    CHECK (quantity > 0),
    CHECK (unit_price >= 0),
    CHECK (total_price >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE od_order_item_topping (
    id CHAR(36) NOT NULL PRIMARY KEY,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    order_item_id CHAR(36) NOT NULL,
    topping_id CHAR(36) NULL,
    topping_code VARCHAR(50) NOT NULL,
    topping_name VARCHAR(150) NOT NULL,
    quantity INT NOT NULL DEFAULT 1,
    unit_price DECIMAL(12,2) NOT NULL,
    total_price DECIMAL(12,2) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by CHAR(36) NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_by CHAR(36) NULL,
    CONSTRAINT fk_od_item_topping_item FOREIGN KEY (order_item_id) REFERENCES od_order_item(id) ON DELETE CASCADE,
    CONSTRAINT fk_od_item_topping_topping FOREIGN KEY (topping_id) REFERENCES pr_topping(id) ON DELETE SET NULL,
    INDEX idx_od_item_topping_item (order_item_id),
    CHECK (quantity > 0),
    CHECK (unit_price >= 0),
    CHECK (total_price >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE od_order_status_history (
    id CHAR(36) NOT NULL PRIMARY KEY,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    order_id CHAR(36) NOT NULL,
    old_status VARCHAR(30) NULL,
    new_status VARCHAR(30) NOT NULL,
    reason VARCHAR(255) NULL,
    changed_by CHAR(36) NULL,
    changed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_by CHAR(36) NULL,
    CONSTRAINT fk_od_status_history_order FOREIGN KEY (order_id) REFERENCES od_order(id) ON DELETE CASCADE,
    CONSTRAINT fk_od_status_history_actor FOREIGN KEY (changed_by) REFERENCES ia_account(id) ON DELETE SET NULL,
    INDEX idx_od_status_history_order_changed (order_id, changed_at),
    INDEX idx_od_status_history_status (new_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
